# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/victor/SolarRAT_Driver/SolarRAT_Driver.srcs/sources_1/ip/photoresistor_xadc/photoresistor_xadc.xci
# IP: The module: 'photoresistor_xadc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/victor/SolarRAT_Driver/SolarRAT_Driver.srcs/sources_1/ip/photoresistor_xadc/photoresistor_xadc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'photoresistor_xadc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/victor/SolarRAT_Driver/SolarRAT_Driver.srcs/sources_1/ip/photoresistor_xadc/photoresistor_xadc.xdc
# XDC: The top module name and the constraint reference have the same name: 'photoresistor_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/victor/SolarRAT_Driver/SolarRAT_Driver.srcs/sources_1/ip/photoresistor_xadc/photoresistor_xadc.xci
# IP: The module: 'photoresistor_xadc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/victor/SolarRAT_Driver/SolarRAT_Driver.srcs/sources_1/ip/photoresistor_xadc/photoresistor_xadc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'photoresistor_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/victor/SolarRAT_Driver/SolarRAT_Driver.srcs/sources_1/ip/photoresistor_xadc/photoresistor_xadc.xdc
# XDC: The top module name and the constraint reference have the same name: 'photoresistor_xadc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
